### PR TITLE
Update RK pointer and make SBANavigationFormStep init public

### PR DESCRIPTION
**Pull request by syoung-smallwisdom**

### CODE REVIEW

**Comment by syoung-smallwisdom** [comment]
@joshbruhin I've added ability to set a learnMoreAction on the base implementation for `SBANavigableQuestionStep` and `SBANavigableFormStep`. This should allow you to use the learn more action with form items.

Note: the default keys are `learnMoreHTMLContentURL` and `learnMoreButtonText`.

**Review by Erin-Mounts — APPROVED** [review]
looks good

**Comment by joshbruhin** [comment]
@syoung-smallwisdom can you update BridgeAppSDK with the new factory pointer?

**Comment by joshbruhin** [comment]
Oh, wait, I see you opened a PR a bit ago. thanks

**Pull request merged**
