### PR TITLE
Move custom Elevate UI to BridgeAppSDK (ResearchUXFactory)

### PR DESCRIPTION
**Pull request by joshbruhin**
1) Move classes from 'Elevate' to 'ResearchUXFactory', rename as necessary. For example: 'ElevateStepViewController' -> 'SBAGenericStepViewController'
'ElevatePageStepViewController' -> 'SBAGenericPageStepViewController'
'ElevateStepTableData' -> 'SBAGenericStepDataSource'
'ElevateChoiceTableViewCell' -> 'SBAStepChoiceTableViewCell'
'ElevateStepHeaderView' -> 'SBAStepHeaderView'
'ElevateStepNavigationView' -> 'SBAStepNavigationView'
'ElevateStepProgressView' -> 'SBAStepProgressView'

2) Move some classes from 'BridgeAppSDK' to 'ResearchUXFactory'
‘SBARoundedButton’
‘SBAShadowGradient’
‘SBAUnderlinedButton’
‘UIColor+BridgeKeyNames’

3) Add ‘SBAVisualConsentStep’ for the consent scenes, which is a ‘ORKPageStep’. It creates a ‘SBAInstructionStep’ for each consent scene from the ‘ORKConsentDocument’. Also, modify ‘SBABaseSurveyFactory’ to return the new ‘SBAVisualConsentStep’.

4) Add ‘UIFont+BridgeKeyNames’ style class for use similar to the UIColor style class being used, both of which can be overridden by the app project.

5) Move ‘UIView+LayoutExtensions’ from ‘Elevate’ to ‘ResearchUXFactory’ and document, rename and refactor.

6) Add ‘SBAFormStep’ to return our new ‘SBAGenericStepViewController class for ORKFormSteps.

7) Modify the ‘SBANavigationFormStep’ to return our new ‘SBAGenericStepViewController’ class.

### CODE REVIEW

**Comment by syoung-smallwisdom** [comment]
@joshbruhin Could you please look to consolidate your changes in BridgeAppSDK instead? Thanks

**Comment by joshbruhin** [comment]
Yep, just about done.

**Comment by syoung-smallwisdom** [comment]
@joshbruhin Should I close this PR then? Sorry, I'm confused. Thanks.

**Comment by joshbruhin** [comment]
yes, it can be closed. I'll do that.

**Pull request closed without merging**
